"""Review models

Revision ID: 5458e83bce22
Revises: 
Create Date: 2024-08-09 13:12:07.732414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5458e83bce22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unit_types')),
    sa.UniqueConstraint('name', name=op.f('uq_unit_types_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('for_sale', 'for_rent', native_enum=False), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('units', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('available', 'sold', 'rented', native_enum=False), nullable=True),
    sa.Column('unit_type_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['unit_type_id'], ['unit_types.id'], name=op.f('fk_properties_unit_type_id_unit_types')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_properties_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_properties'))
    )
    op.create_table('purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('mpesa_code', sa.String(), nullable=True),
    sa.Column('purchased_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_purchases_property_id_properties')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_purchases_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchases'))
    )
    op.create_table('rented',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_number', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('rented_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_rented_property_id_properties')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_rented_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rented'))
    )
    op.create_table('rental_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rented_id', sa.Integer(), nullable=True),
    sa.Column('month', sa.String(), nullable=True),
    sa.Column('mpesa_code', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rented_id'], ['rented.id'], name=op.f('fk_rental_payments_rented_id_rented')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rental_payments'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rental_payments')
    op.drop_table('rented')
    op.drop_table('purchases')
    op.drop_table('properties')
    op.drop_table('users')
    op.drop_table('unit_types')
    # ### end Alembic commands ###
