"""user migration

Revision ID: a3e53981df14
Revises: 5458e83bce22
Create Date: 2024-08-09 18:08:54.809351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3e53981df14'
down_revision = '5458e83bce22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('role', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_users_contact'), ['contact'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_contact'), type_='unique')
        batch_op.drop_column('created_at')
        batch_op.drop_column('role')
        batch_op.drop_column('contact')

    # ### end Alembic commands ###
