"""add amount

Revision ID: c6af782a4509
Revises: 2e355ddd80c1
Create Date: 2024-08-16 12:17:08.310306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6af782a4509'
down_revision = '2e355ddd80c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rented', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rented', schema=None) as batch_op:
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
